version: "3.9"
services:
  db:
    image: mysql:8.0.28-debian
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: comunidadlsa
  backend:
    build: backend
    restart: always
    environment:
      DB_NAME: comunidadlsa
    volumes:
      - ./src/backend:/app
  frontend:
    build: frontend
    volumes:
      - ./src/backend:/src-backend
      - ./src/frontend:/src-frontend
    ports:
      - "80:80"
      - "443:443"
